var CATALOGUE = [
  // ===== AUSTRALIA - Exits =====
  {m:"AU", cat:"Exit", nec:"Heal", name:"CSL", type:"IPO", year:"1994", value:"~$85bn cap", ctp:"ASX", what:"Plasma, vaccines, biotherapies.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"ResMed", type:"IPO", year:"1995", value:"$500m+", ctp:"NYSE", what:"Sleep and respiratory devices.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Cochlear", type:"IPO", year:"1995", value:"$500m+", ctp:"ASX", what:"Hearing implants.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Pro Medicus", type:"IPO", year:"2000", value:"mega-cap", ctp:"ASX", what:"Visage radiology imaging software.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Mesoblast", type:"IPO", year:"2004", value:"$500m+", ctp:"ASX / Nasdaq", what:"Allogeneic cell therapy.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Nanosonics", type:"IPO", year:"2007", value:"$500m+", ctp:"ASX", what:"Ultrasound-probe disinfection.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"HeartWare", type:"M&A", year:"2016", value:"$1,100m", ctp:"Medtronic", what:"Implantable heart pump.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Sirtex Medical", type:"M&A", year:"2018", value:"~$1,400m", ctp:"China Grand", what:"Y-90 liver-cancer microspheres.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Eucalyptus", type:"M&A", year:"2026", value:"~$1,150m", ctp:"Hims & Hers", what:"Digital health / telehealth.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Spinifex Pharma", type:"M&A", year:"2015", value:"$312m upfront (to ~$700m+)", ctp:"Novartis", what:"Neuropathic pain (EMA401).", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Fibrotech", type:"M&A", year:"2014", value:"to $558m", ctp:"Shire", what:"Anti-fibrosis therapeutics.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Elastagen", type:"M&A", year:"2018", value:"$261m", ctp:"Allergan", what:"Recombinant tropoelastin.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"MedicalDirector", type:"M&A", year:"2021", value:"$255m", ctp:"Telstra Health", what:"Clinical software.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Hatchtech", type:"M&A", year:"2016", value:"to $279m", ctp:"Dr Reddy's", what:"Head-lice treatment.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Peplin", type:"M&A", year:"2009", value:"~$287m", ctp:"LEO Pharma", what:"Actinic keratosis gel (Picato).", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"ChemGenex", type:"M&A", year:"2011", value:"~$225m", ctp:"Cephalon / Teva", what:"Leukaemia drug.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Acrux", type:"Licence", year:"2010", value:"to ~$335m", ctp:"Eli Lilly", what:"Transdermal testosterone.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"ResApp Health", type:"M&A", year:"2022", value:"$120m", ctp:"Pfizer", what:"Acoustic respiratory diagnostics.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Telix Pharmaceuticals", type:"IPO", year:"2017 / 2024", value:"$500m+", ctp:"ASX / Nasdaq", what:"Targeted radiopharmaceuticals.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Avita Medical", type:"IPO", year:"2020", value:"$500m+", ctp:"ASX / Nasdaq", what:"ReCell spray-on skin.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Neuren Pharma", type:"IPO", year:"2005", value:"$500m+", ctp:"ASX", what:"Rett syndrome (DAYBUE).", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Clinuvel", type:"IPO", year:"2019", value:"$500m+", ctp:"ASX", what:"Photoprotection drug.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"4DMedical, Clarity Pharma, Micro-X, EMVision, Atomo Diagnostics, Trajan, Radiopharm, Vitrafy", type:"IPO", year:"2015 to 2024", value:"", ctp:"ASX / Nasdaq", what:"Imaging, radiopharma, diagnostics.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"PolyNovo, Anteris, Immutep, Starpharma, Universal Biosensors", type:"Listed", year:"", value:"", ctp:"ASX / Nasdaq", what:"Scaffolds, valves, immuno, delivery.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Harrison.ai", type:"$500m+ private", year:"2025", value:"~$400m+ raised", ctp:"Private", what:"AI radiology and pathology.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Heal", name:"Vaxxas", type:"Private (raising)", year:"", value:"", ctp:"Private", what:"Needle-free Nanopatch vaccines.", cohort:false},

  {m:"AU", cat:"Exit", nec:"Power", name:"CWP Renewables", type:"M&A", year:"2022", value:"$2,700m", ctp:"Squadron Energy", what:"Wind and solar developer.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Tilt Renewables", type:"M&A", year:"2021", value:"$2,060m", ctp:"PowAR (AGL/QIC/Future Fund)", what:"Renewables generation.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Edify Energy", type:"M&A", year:"2025", value:"$724m", ctp:"CDPQ", what:"Solar and storage.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Infigen Energy", type:"M&A", year:"2020", value:"$640m", ctp:"Iberdrola", what:"Wind generation.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Genex Power", type:"M&A", year:"2024", value:"$229m", ctp:"J-POWER", what:"Pumped hydro and solar.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Sun Cable", type:"Private asset sale", year:"2023", value:"n/d", ctp:"Cannon-Brookes", what:"Australia to Asia solar link.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Power", name:"Novonix", type:"IPO / ADR", year:"2015 / 2021", value:"$500m+ peak", ctp:"ASX / Nasdaq", what:"Synthetic graphite anode.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Vulcan Energy", type:"IPO", year:"", value:"$500m+ peak", ctp:"ASX", what:"Zero-carbon lithium.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Power", name:"Calix, Australian Strategic Materials, Gelion, Li-S Energy, Vast Renewables", type:"IPO", year:"2018 to 2023", value:"", ctp:"ASX / Nasdaq / AIM", what:"Materials, batteries, CSP.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Power", name:"Silex Systems", type:"Listed", year:"", value:"", ctp:"ASX", what:"Laser uranium enrichment.", cohort:false},

  {m:"AU", cat:"Exit", nec:"Eat", name:"Costa Group", type:"M&A", year:"2024", value:"~$1,000m to 1,500m", ctp:"Private equity", what:"Horticulture.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Tassal Group", type:"M&A", year:"2022", value:"$1,080m", ctp:"Cooke Inc", what:"Salmon aquaculture.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Bellamy's", type:"M&A", year:"2019", value:"$1,000m", ctp:"China Mengniu", what:"Infant formula.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Real Pet Food", type:"M&A", year:"2017", value:"$770m", ctp:"New Hope", what:"Pet food.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Huon Aquaculture", type:"M&A", year:"2021", value:"$313m", ctp:"JBS", what:"Salmon aquaculture.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Capilano Honey", type:"M&A", year:"2018", value:"$137m", ctp:"Private equity", what:"Honey.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Agworld", type:"M&A", year:"2021", value:"$100m", ctp:"Semios", what:"Farm data platform.", cohort:true},
  {m:"AU", cat:"Exit", nec:"Eat", name:"a2 Milk", type:"IPO", year:"2004", value:"$500m+", ctp:"ASX / NZX", what:"A2-protein dairy.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Eat", name:"v2food", type:"$500m+ private", year:"", value:"~$185m raised", ctp:"Private (CSIRO spinout)", what:"Plant-based meat.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Eat", name:"SwarmFarm Robotics", type:"Private", year:"2025", value:"", ctp:"Private", what:"Autonomous broadacre robots.", cohort:false},
  {m:"AU", cat:"Exit", nec:"Eat", name:"Rubicon Water, Nuchev, Wide Open Agriculture", type:"IPO", year:"2018 to 2021", value:"", ctp:"ASX", what:"Irrigation control, dairy, regen ag.", cohort:true},

  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Aconex", type:"M&A", year:"2018", value:"~$1,200m", ctp:"Oracle", what:"Construction collaboration cloud.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Nearmap", type:"M&A", year:"2022", value:"~$1,060m", ctp:"Private equity", what:"Aerial imagery + AI.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Nuix", type:"IPO", year:"2020", value:"~$1,800m cap", ctp:"ASX", what:"Investigative data analytics.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Appen", type:"IPO", year:"2015", value:"$500m+ peak", ctp:"ASX", what:"AI training data.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Fleet Space", type:"$500m+ private", year:"2024", value:"~$800m", ctp:"Private", what:"Minerals-exploration satellites.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Q-CTRL", type:"$500m+ private", year:"2025", value:"~$1bn+ (unverified)", ctp:"Private", what:"Quantum control software.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Silicon Quantum Computing", type:"Private", year:"", value:"~$94m raised", ctp:"Private (UNSW)", what:"Silicon-qubit quantum computer.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Gilmour Space", type:"Private (Series E $217m)", year:"2024", value:"near-unicorn", ctp:"Private", what:"Orbital launch.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Audinate, Seeing Machines, BrainChip", type:"IPO / listed", year:"2017 to now", value:"", ctp:"ASX / AIM", what:"Audio-over-IP, driver AI, neuromorphic.", cohort:false},
  {m:"AU", cat:"Exit", nec:"DeepTech", name:"Advanced Navigation, Emesent, Myriota, Skykraft", type:"Private", year:"", value:"", ctp:"Private", what:"Navigation, drone LiDAR, satellite IoT/ATM.", cohort:false},

  // ===== AUSTRALIA - Hardware =====
  {m:"AU", cat:"Hardware", name:"WiFi WLAN chipset", detail:"CSIRO, 1990s"},
  {m:"AU", cat:"Hardware", name:"polymer banknotes", detail:"CSIRO/RBA, 1988"},
  {m:"AU", cat:"Hardware", name:"multi-channel cochlear implant", detail:"Clark/Cochlear"},
  {m:"AU", cat:"Hardware", name:"PERC solar cell", detail:"Green/UNSW, now >90% of panels"},
  {m:"AU", cat:"Hardware", name:"ReCell spray-on skin", detail:"Wood/Avita"},
  {m:"AU", cat:"Hardware", name:"SIR-Spheres Y-90 microspheres", detail:"Sirtex"},
  {m:"AU", cat:"Hardware", name:"Nanopatch needle-free delivery", detail:"Kendall/UQ/Vaxxas"},
  {m:"AU", cat:"Hardware", name:"3D-printed titanium sternum and ribs", detail:"Anatomics/CSIRO, 2015"},
  {m:"AU", cat:"Hardware", name:"extended-wear silicone-hydrogel contact lenses", detail:"Holden"},
  {m:"AU", cat:"Hardware", name:"single-atom silicon qubit", detail:"Simmons/UNSW/SQC"},
  {m:"AU", cat:"Hardware", name:"room-temperature diamond quantum modules", detail:"Quantum Brilliance"},
  {m:"AU", cat:"Hardware", name:"Akida neuromorphic chip", detail:"BrainChip"},
  {m:"AU", cat:"Hardware", name:"WiFi HaLow IoT silicon", detail:"Morse Micro"},
  {m:"AU", cat:"Hardware", name:"spectrum-scan LiDAR", detail:"Baraja"},
  {m:"AU", cat:"Hardware", name:"Hovermap SLAM", detail:"Emesent/CSIRO"},
  {m:"AU", cat:"Hardware", name:"vanadium redox flow battery", detail:"Skyllas-Kazacos/UNSW"},
  {m:"AU", cat:"Hardware", name:"zinc-bromine flow battery", detail:"Redflow"},
  {m:"AU", cat:"Hardware", name:"copper solar metallisation", detail:"SunDrive"},
  {m:"AU", cat:"Hardware", name:"molten-silicon thermal storage", detail:"1414 Degrees"},
  {m:"AU", cat:"Hardware", name:"cold-spray titanium AM", detail:"Titomic"},
  {m:"AU", cat:"Hardware", name:"wire-arc metal AM", detail:"AML3D"},
  {m:"AU", cat:"Hardware", name:"Hendra virus vaccine", detail:"CSIRO, 2012"},
  {m:"AU", cat:"Hardware", name:"CL1 biological computer", detail:"Cortical Labs, 2024"},

  // ===== AUSTRALIA - Software =====
  {m:"AU", cat:"Software", name:"Visage 7 server-side 3D imaging", detail:"Pro Medicus"},
  {m:"AU", cat:"Software", name:"Aconex collaboration platform", detail:""},
  {m:"AU", cat:"Software", name:"Nearmap AI location intelligence", detail:""},
  {m:"AU", cat:"Software", name:"Nuix Engine", detail:""},
  {m:"AU", cat:"Software", name:"Annalise.ai chest X-ray and brain CT triage", detail:"Harrison.ai"},
  {m:"AU", cat:"Software", name:"franklin.ai histopathology", detail:""},
  {m:"AU", cat:"Software", name:"Boulder Opal / Fire Opal quantum control", detail:"Q-CTRL"},
  {m:"AU", cat:"Software", name:"Emesent Cortex/Aura autonomy", detail:""},
  {m:"AU", cat:"Software", name:"Appen labelling platform", detail:""},
  {m:"AU", cat:"Software", name:"Seeing Machines FOVIO driver monitoring", detail:""},
  {m:"AU", cat:"Software", name:"Advanced Navigation sensor fusion", detail:""},
  {m:"AU", cat:"Software", name:"Presien Blindsight hazard vision", detail:""},
  {m:"AU", cat:"Software", name:"The Yield Sensing+ agronomy", detail:""},
  {m:"AU", cat:"Software", name:"Fleet Space ExoSphere geophysics", detail:""},

  // ===== AUSTRALIA - IP =====
  {m:"AU", cat:"IP", name:"CSIRO WiFi patent US 5,487,069", detail:"filed 1993; ~$430m to 1bn in settlements"},
  {m:"AU", cat:"IP", name:"HPV virus-like-particle vaccine to Gardasil", detail:"Frazer & Zhou, UQ/CSL/Merck, 1991"},
  {m:"AU", cat:"IP", name:"neuraminidase structure to zanamivir/Relenza", detail:"Colman, CSIRO/Biota/GSK"},
  {m:"AU", cat:"IP", name:"multi-channel cochlear implant patents", detail:"Clark"},
  {m:"AU", cat:"IP", name:"ReCell autologous cell-spray patents", detail:"Wood"},
  {m:"AU", cat:"IP", name:"PERC solar-cell patents", detail:"Green/UNSW"},
  {m:"AU", cat:"IP", name:"polymer-banknote and optically-variable-device patents", detail:"CSIRO/RBA"},
  {m:"AU", cat:"IP", name:"vanadium redox flow patents", detail:"UNSW"},
  {m:"AU", cat:"IP", name:"SIR-Spheres Y-90 IP", detail:"Sirtex"},
  {m:"AU", cat:"IP", name:"atomic-precision silicon-qubit fabrication IP", detail:"SQC/UNSW"},
  {m:"AU", cat:"IP", name:"Gene Shears ribozyme IP", detail:"CSIRO"},
  {m:"AU", cat:"IP", name:"Nanopatch delivery IP", detail:"UQ/Vaxxas"},
  {m:"AU", cat:"IP", name:"3D-printed patient-specific implant IP", detail:"Anatomics/CSIRO"},

  // ===== JAPAN - Exits =====
  {m:"JP", cat:"Exit", nec:"Heal", name:"Sysmex", type:"Listed (scaled 2000s)", year:"", value:"~$15bn+ cap", ctp:"TSE", what:"Haematology analysers, IVD.", cohort:false},
  {m:"JP", cat:"Exit", nec:"Heal", name:"PeptiDream", type:"IPO", year:"2013", value:"$52m raised, >$1.4bn cap", ctp:"TSE Mothers", what:"Macrocyclic-peptide drug discovery.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Heal", name:"Cyberdyne", type:"IPO", year:"2014", value:"$89m raised", ctp:"TSE Mothers", what:"HAL exoskeleton.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Heal", name:"PHC Holdings", type:"IPO", year:"2021", value:"", ctp:"TSE 1st", what:"Medical devices and diagnostics.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Heal", name:"JMDC, Medley, MedPeer, CellSource, Modalis, SUSMED, Heartseed, Cuorips", type:"IPO", year:"2014 to 2024", value:"", ctp:"TSE Mothers/Growth", what:"Health data, telemedicine, cell/gene, regenerative.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Heal", name:"OriCiro Genomics", type:"M&A", year:"2023", value:"$85m", ctp:"Moderna", what:"Cell-free enzymatic DNA synthesis.", cohort:false},
  {m:"JP", cat:"Exit", nec:"Heal", name:"LPIXEL", type:"Private", year:"2014 to now", value:"", ctp:"Private", what:"AI medical imaging (SaMD).", cohort:false},
  {m:"JP", cat:"Exit", nec:"Heal", name:"Ubie", type:"Late private", year:"2017 to now", value:"", ctp:"Private", what:"AI symptom checker.", cohort:false},
  {m:"JP", cat:"Exit", nec:"Heal", name:"Craif", type:"Series C", year:"2025", value:"~$100m val", ctp:"Private (Nagoya spinout)", what:"Urine-miRNA cancer detection.", cohort:false},

  {m:"JP", cat:"Exit", nec:"Power", name:"Japan Renewable Energy", type:"M&A", year:"2021", value:"$1,800m", ctp:"ENEOS", what:"Renewables IPP.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Power", name:"RENOVA", type:"IPO", year:"2017", value:"", ctp:"TSE Mothers", what:"Renewables developer.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Power", name:"Power X", type:"IPO", year:"2024", value:"", ctp:"TSE Growth", what:"Grid storage, battery tanker.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Power", name:"Digital Grid, ENECHANGE, TESS Holdings, Microwave Chemical, Rezil, Informetis", type:"IPO", year:"2020 to 2025", value:"", ctp:"TSE Growth", what:"Grid, energy retail, process electrification.", cohort:true},

  {m:"JP", cat:"Exit", nec:"Eat", name:"Spiber", type:"$500m+ private", year:"2021", value:"~$1,220m val", ctp:"Private", what:"Brewed-protein biomaterial.", cohort:false},
  {m:"JP", cat:"Exit", nec:"Eat", name:"BASE FOOD, Foodison, Kuradashi, Ame Kaze Taiyo", type:"IPO", year:"2022 to 2023", value:"", ctp:"TSE Growth", what:"Nutrition, seafood distribution, food loss, rural produce.", cohort:true},
  {m:"JP", cat:"Exit", nec:"Eat", name:"Farmnote", type:"Private", year:"2013 to now", value:"", ctp:"Private", what:"Livestock herd management + AI.", cohort:false},
  {m:"JP", cat:"Exit", nec:"Eat", name:"inaho, AGRIST", type:"Private", year:"2017 to now", value:"", ctp:"Private", what:"Robotic vegetable harvesting.", cohort:false},

  {m:"JP", cat:"Exit", nec:"DeepTech", name:"Preferred Networks", type:"$500m+ private", year:"2010s", value:">$2bn val", ctp:"Private (Toyota, Fanuc)", what:"Industrial and robotics AI.", cohort:false},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"Sakana AI", type:"$500m+ private", year:"2024", value:"~$1.5 to 2.65bn val", ctp:"Private", what:"Foundation models, model merging.", cohort:false},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"ispace", type:"IPO", year:"2023", value:"~$700m debut cap", ctp:"TSE Growth", what:"Lunar landers.", cohort:true},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"Astroscale", type:"IPO", year:"2024", value:"~$443m raised", ctp:"TSE Growth", what:"Orbital servicing, debris removal.", cohort:false},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"iQPS, Axelspace", type:"IPO", year:"2023 / 2025", value:"", ctp:"TSE Growth", what:"SAR and optical EO satellites.", cohort:false},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"Synspective", type:"$500m+ private", year:"2022", value:"~$1,100m val", ctp:"Private", what:"Small SAR satellites.", cohort:false},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"Rapidus", type:"Consortium", year:"2022 to now", value:"", ctp:"Sony/Toyota/SoftBank et al.", what:"2nm logic foundry.", cohort:false},
  {m:"JP", cat:"Exit", nec:"DeepTech", name:"Telexistence", type:"Private (Series B $170m)", year:"2023", value:"", ctp:"Private (Ricoh)", what:"AI restocking robots.", cohort:false},

  // ===== JAPAN - Hardware =====
  {m:"JP", cat:"Hardware", name:"Stacked 3-layer BSI CMOS image sensor", detail:"Sony, 2017"},
  {m:"JP", cat:"Hardware", name:"Exmor back-illuminated CMOS", detail:"Sony, 2008"},
  {m:"JP", cat:"Hardware", name:"organic-film CMOS", detail:"Panasonic/Fujifilm"},
  {m:"JP", cat:"Hardware", name:"HAL exoskeleton", detail:"Cyberdyne/Tsukuba"},
  {m:"JP", cat:"Hardware", name:"automotive solid-state battery", detail:"Toyota/Panasonic, target 2027"},
  {m:"JP", cat:"Hardware", name:"first commercial lithium-ion cell", detail:"Asahi Kasei / Yoshino, 1985"},
  {m:"JP", cat:"Hardware", name:"carbon fibre TORAYCA", detail:"Toray"},
  {m:"JP", cat:"Hardware", name:"prime silicon wafers", detail:"Shin-Etsu, SUMCO, ~90% share"},
  {m:"JP", cat:"Hardware", name:"EUV/ArF photoresists", detail:"JSR, Tokyo Ohka, ~80% share"},
  {m:"JP", cat:"Hardware", name:"industrial robots and CNC", detail:"Fanuc"},
  {m:"JP", cat:"Hardware", name:"Motoman robots", detail:"Yaskawa"},
  {m:"JP", cat:"Hardware", name:"AIBO/QRIO", detail:"Sony"},
  {m:"JP", cat:"Hardware", name:"Pepper humanoid", detail:"SoftBank"},
  {m:"JP", cat:"Hardware", name:"miSignal urine-miRNA assay", detail:"Craif"},
  {m:"JP", cat:"Hardware", name:"SAR small-sat bus", detail:"Synspective/iQPS"},
  {m:"JP", cat:"Hardware", name:"HAKUTO-R lunar lander", detail:"ispace"},
  {m:"JP", cat:"Hardware", name:"2nm gate-all-around prototype", detail:"Rapidus, 2025"},

  // ===== JAPAN - Software =====
  {m:"JP", cat:"Software", name:"Chainer define-by-run DL framework", detail:"Preferred Networks, 2015; influenced PyTorch"},
  {m:"JP", cat:"Software", name:"ChainerMN distributed training", detail:""},
  {m:"JP", cat:"Software", name:"Matlantis universal atomistic simulator", detail:"PFN"},
  {m:"JP", cat:"Software", name:"Evolutionary Model Merge", detail:"Sakana, 2024"},
  {m:"JP", cat:"Software", name:"The AI Scientist", detail:"Sakana, 2024"},
  {m:"JP", cat:"Software", name:"EIRL medical-imaging AI", detail:"LPIXEL"},
  {m:"JP", cat:"Software", name:"Ubie triage engine", detail:""},
  {m:"JP", cat:"Software", name:"Craif miRNA classifier", detail:""},
  {m:"JP", cat:"Software", name:"Farmnote herd analytics", detail:""},
  {m:"JP", cat:"Software", name:"inaho harvest vision", detail:""},
  {m:"JP", cat:"Software", name:"ABEJA industrial AI/MLOps platform", detail:""},
  {m:"JP", cat:"Software", name:"PLaMo Japanese LLM", detail:"PFN"},

  // ===== JAPAN - IP =====
  {m:"JP", cat:"IP", name:"iPS-cell reprogramming / Yamanaka factors", detail:"Kyoto University, patent 2008, Nobel 2012"},
  {m:"JP", cat:"IP", name:"PD-1 checkpoint to Opdivo/nivolumab", detail:"Honjo & Ono Pharmaceutical, approval 2014"},
  {m:"JP", cat:"IP", name:"Green Fluorescent Protein discovery", detail:"Shimomura, Nobel 2008"},
  {m:"JP", cat:"IP", name:"high-brightness blue InGaN LED", detail:"Nakamura/Nichia, 1993, Nobel 2014"},
  {m:"JP", cat:"IP", name:"first rechargeable Li-ion battery patent JP 1989293", detail:"Yoshino/Asahi Kasei, 1985, Nobel 2019"},
  {m:"JP", cat:"IP", name:"stacked/back-illuminated CMOS sensor patents", detail:"Sony, 2008 to 2017"},
  {m:"JP", cat:"IP", name:"LiCoO2 cathode chemistry commercialised in Japan", detail:"Sony, 1991"},
  {m:"JP", cat:"IP", name:"all-solid-state battery portfolio", detail:"Toyota/Panasonic, world's largest share"},
  {m:"JP", cat:"IP", name:"silicon-wafer and photoresist process IP", detail:"Shin-Etsu"},

  // ===== NEW ZEALAND - Exits =====
  {m:"NZ", cat:"Exit", nec:"Heal", name:"Fisher & Paykel Healthcare", type:"IPO", year:"2001", value:"~$12bn+ cap", ctp:"NZX / ASX", what:"Respiratory humidification and masks.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Heal", name:"Aroa Biosurgery", type:"IPO", year:"2020", value:"A$225m", ctp:"ASX", what:"Ovine-ECM soft-tissue regeneration.", cohort:true},
  {m:"NZ", cat:"Exit", nec:"Heal", name:"Volpara Health", type:"IPO / M&A", year:"2016 / 2024", value:"$193m (acq.)", ctp:"ASX; Lunit", what:"Breast-imaging AI.", cohort:true},
  {m:"NZ", cat:"Exit", nec:"Heal", name:"Pacific Edge", type:"Listed", year:"~2003", value:"", ctp:"NZX / ASX", what:"Cxbladder genomic urine test.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Heal", name:"AFT Pharmaceuticals, Adherium", type:"IPO", year:"2015", value:"", ctp:"NZX / ASX", what:"Pharma; connected inhaler.", cohort:true},
  {m:"NZ", cat:"Exit", nec:"Heal", name:"Blis Technologies", type:"IPO", year:"2001", value:"", ctp:"NZX", what:"Probiotic strains.", cohort:false},

  {m:"NZ", cat:"Exit", nec:"Power", name:"LanzaTech", type:"IPO (SPAC)", year:"2023", value:"~$2,200m", ctp:"Nasdaq", what:"Gas fermentation to fuels and chemicals.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Power", name:"PowerbyProxi", type:"M&A", year:"2017", value:"$100m+", ctp:"Apple", what:"Qi wireless power (Auckland spinout).", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Power", name:"Invenco", type:"M&A", year:"2022", value:"$80m", ctp:"Vontier", what:"Fuel-forecourt payment hardware.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Power", name:"Wellington Drive / AoFrio", type:"Listed", year:"", value:"", ctp:"NZX", what:"EC motors, refrigeration IoT.", cohort:false},

  {m:"NZ", cat:"Exit", nec:"Eat", name:"a2 Milk", type:"IPO", year:"2004", value:"~$3 to 5bn cap", ctp:"NZX / ASX", what:"A1-free milk and formula.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"Halter", type:"$500m+ private", year:"2025", value:"~$2bn (Series E)", ctp:"Private", what:"GPS collars, virtual fencing, behavioural AI.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"Synlait Milk", type:"IPO", year:"2013", value:"~$305m raise", ctp:"NZX / ASX", what:"Dairy processing.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"Comvita", type:"IPO", year:"2003", value:"", ctp:"NZX", what:"Manuka honey, wellness.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"Livestock Improvement Corp", type:"Listed", year:"2004", value:"", ctp:"NZX", what:"Dairy genetics co-op.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"Compac Sorting", type:"M&A", year:"2016", value:"NZ$70m", ctp:"TOMRA", what:"Optical produce grading.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"BBC Technologies", type:"M&A", year:"2018", value:"NZ$67m", ctp:"TOMRA", what:"Berry sorting.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"Robotics Plus", type:"M&A (staged)", year:"2018 to 2025", value:"", ctp:"Yamaha", what:"Orchard robotics.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"Eat", name:"NZ King Salmon, Seeka", type:"IPO / listed", year:"2016 to now", value:"", ctp:"NZX", what:"Aquaculture, kiwifruit.", cohort:false},

  {m:"NZ", cat:"Exit", nec:"DeepTech", name:"Rocket Lab", type:"IPO (SPAC)", year:"2021", value:"~$4,100m EV", ctp:"Nasdaq", what:"Small-launch rockets and space systems.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"DeepTech", name:"Dawn Aerospace", type:"$500m+ private", year:"2026", value:"~$200m (NZ$335m)", ctp:"Private", what:"Reusable spaceplane, green thrusters.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"DeepTech", name:"Rakon", type:"IPO", year:"2006", value:"", ctp:"NZX", what:"Precision oscillators.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"DeepTech", name:"Scott Technology", type:"Listed", year:"", value:"", ctp:"NZX", what:"Meat-processing robotics.", cohort:false},
  {m:"NZ", cat:"Exit", nec:"DeepTech", name:"Soul Machines", type:"High raise, no exit", year:"2016 to 2026", value:"$135m+ raised", ctp:"Receivership 2026", what:"AI digital humans (failed).", cohort:false},
  {m:"NZ", cat:"Exit", nec:"DeepTech", name:"Gentrack, EROAD, ikeGPS", type:"IPO", year:"2014", value:"", ctp:"NZX", what:"Utility billing, telematics, geospatial.", cohort:false},

  // ===== NEW ZEALAND - Hardware =====
  {m:"NZ", cat:"Hardware", name:"Rutherford electric-turbopump 3D-printed rocket engine", detail:"Rocket Lab"},
  {m:"NZ", cat:"Hardware", name:"Electron launch vehicle", detail:""},
  {m:"NZ", cat:"Hardware", name:"Optiflow nasal high flow and F&P humidifiers", detail:""},
  {m:"NZ", cat:"Hardware", name:"PowerbyProxi wireless-power modules", detail:""},
  {m:"NZ", cat:"Hardware", name:"StretchSense capacitive motion-capture sensors", detail:""},
  {m:"NZ", cat:"Hardware", name:"Z01 superconducting magnetorquer", detail:"Zenno, first superconducting magnet in space"},
  {m:"NZ", cat:"Hardware", name:"Aurora spaceplane and green bipropellant thrusters", detail:"Dawn"},
  {m:"NZ", cat:"Hardware", name:"Kea Atmos solar stratospheric aircraft", detail:""},
  {m:"NZ", cat:"Hardware", name:"Ubco 2x2 electric utility bike", detail:""},
  {m:"NZ", cat:"Hardware", name:"Aporo packer and Prospr orchard vehicle", detail:"Robotics Plus"},
  {m:"NZ", cat:"Hardware", name:"optical produce sorters", detail:"Compac/BBC"},
  {m:"NZ", cat:"Hardware", name:"robotic meat boning", detail:"Scott"},
  {m:"NZ", cat:"Hardware", name:"quartz oscillators", detail:"Rakon"},
  {m:"NZ", cat:"Hardware", name:"bio-refinery metal recovery", detail:"Mint Innovation"},
  {m:"NZ", cat:"Hardware", name:"biographite from forestry waste", detail:"CarbonScape"},
  {m:"NZ", cat:"Hardware", name:"solar GPS behavioural collar", detail:"Halter"},
  {m:"NZ", cat:"Hardware", name:"Endoform ovine-ECM biomaterial", detail:"Aroa"},
  {m:"NZ", cat:"Hardware", name:"Smartinhaler", detail:"Adherium"},
  {m:"NZ", cat:"Hardware", name:"EC refrigeration motors", detail:"Wellington Drive"},
  {m:"NZ", cat:"Hardware", name:"electric-fence and EID hardware", detail:"Gallagher"},

  // ===== NEW ZEALAND - Software =====
  {m:"NZ", cat:"Software", name:"Cowgorithm behavioural AI and virtual fencing", detail:"Halter"},
  {m:"NZ", cat:"Software", name:"digital humans / Human OS / Baby X", detail:"Soul Machines"},
  {m:"NZ", cat:"Software", name:"breast-density and screening AI", detail:"Volpara"},
  {m:"NZ", cat:"Software", name:"Cxbladder genomic classifier", detail:"Pacific Edge"},
  {m:"NZ", cat:"Software", name:"GeoAI platform", detail:"Orbica"},
  {m:"NZ", cat:"Software", name:"Onside biosecurity network", detail:""},
  {m:"NZ", cat:"Software", name:"Cropsy vineyard vine-scanning AI", detail:""},
  {m:"NZ", cat:"Software", name:"BioLumic UV crop-programming", detail:""},
  {m:"NZ", cat:"Software", name:"Nyriad/Exaba GPU compute-storage", detail:""},
  {m:"NZ", cat:"Software", name:"MINDA herd and genomic breeding platform", detail:"LIC"},
  {m:"NZ", cat:"Software", name:"Hailie adherence analytics", detail:"Adherium"},

  // ===== NEW ZEALAND - IP =====
  {m:"NZ", cat:"IP", name:"F&P respiratory humidification and Optiflow patent portfolio", detail:""},
  {m:"NZ", cat:"IP", name:"loosely-coupled resonant wireless-power IP", detail:"PowerbyProxi, acquired by Apple"},
  {m:"NZ", cat:"IP", name:"ovine-forestomach ECM biomaterial patents", detail:"Aroa, first 2008"},
  {m:"NZ", cat:"IP", name:"gas-fermentation IP using engineered Clostridium autoethanogenum", detail:"LanzaTech"},
  {m:"NZ", cat:"IP", name:"electric-turbopump and EBM 3D-printed engine IP", detail:"Rocket Lab"},
  {m:"NZ", cat:"IP", name:"high-temperature superconducting spacecraft magnet", detail:"Zenno"},
  {m:"NZ", cat:"IP", name:"A1/A2 beta-casein protein-typing IP", detail:"a2 Milk"},
  {m:"NZ", cat:"IP", name:"dairy genomic-selection IP", detail:"LIC"},
  {m:"NZ", cat:"IP", name:"UMF-graded manuka-honey bioactive IP", detail:"Comvita"},
  {m:"NZ", cat:"IP", name:"electric-fence energizer IP", detail:"Gallagher"}
];

if (typeof window !== "undefined") { window.CATALOGUE = CATALOGUE; }
